name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  test:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci --force
        
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      
      - name: Create .env file
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL || 'http://localhost:4200' }}" > .env
          echo "TEST_USER_EMAIL=${{ secrets.TEST_USER_EMAIL }}" >> .env
          echo "TEST_USER_PASSWORD=${{ secrets.TEST_USER_PASSWORD }}" >> .env
          echo "TEST_DELETE_EMAIL=${{ secrets.TEST_DELETE_EMAIL }}" >> .env
          echo "TEST_EDIT_EMAIL=${{ secrets.TEST_EDIT_EMAIL }}" >> .env
          echo "TEST_AGE_FILTERS=${{ secrets.TEST_AGE_FILTERS }}" >> .env

      - name: Run Playwright tests (Chromium only)
        run: npx playwright test --project=chromium
        
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14