name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run tests on'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - chromium
          - firefox

env:
  NODE_VERSION: 18

jobs:
  test:
    name: "Playwright Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci --force

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright browsers
        run: |
          if [ "${{ github.event.inputs.browser }}" = "all" ] || [ -z "${{ github.event.inputs.browser }}" ]; then
            npx playwright install chromium firefox --with-deps
          else
            npx playwright install ${{ github.event.inputs.browser }} --with-deps
          fi

      - name: Validate environment variables
        run: |
          if [ -z "${{ secrets.TEST_USER_EMAIL }}" ]; then
            echo "::warning::TEST_USER_EMAIL secret is not set"
          fi
          if [ -z "${{ secrets.TEST_USER_PASSWORD }}" ]; then
            echo "::warning::TEST_USER_PASSWORD secret is not set"
          fi

      - name: Start web server
        run: |
          npm run start:ci &
          SERVER_PID=$!
          echo "SERVER_PID=$SERVER_PID" >> $GITHUB_ENV
          npx wait-on http://localhost:4200 --timeout 120000 --interval 1000
          echo "::notice::Server started successfully on http://localhost:4200"

      - name: Run Playwright tests
        run: |
          if [ "${{ github.event.inputs.browser }}" = "all" ] || [ -z "${{ github.event.inputs.browser }}" ]; then
            npx playwright test --config playwright.ci.config.ts --reporter=html,blob
          else
            npx playwright test --project=${{ github.event.inputs.browser }} --config playwright.ci.config.ts --reporter=html,blob
          fi
        env:
          BASE_URL: ${{ secrets.BASE_URL || 'http://localhost:4200' }}
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
          TEST_DELETE_EMAIL: ${{ secrets.TEST_DELETE_EMAIL }}
          TEST_EDIT_EMAIL: ${{ secrets.TEST_EDIT_EMAIL }}
          TEST_AGE_FILTERS: ${{ secrets.TEST_AGE_FILTERS }}
          CI: true
          NODE_ENV: test

      - name: Stop web server
        if: always()
        run: |
          if [ ! -z "$SERVER_PID" ]; then
            kill $SERVER_PID || true
          fi

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: playwright-report/
          retention-days: 14

      - name: Upload blob report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: blob-report
          path: blob-report/
          retention-days: 1

      - name: Upload traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: traces
          path: test-results/**/trace.zip
          retention-days: 14

      - name: Upload test videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-videos
          path: test-results/
          retention-days: 7

      - name: Comment PR with test results
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const comment = \`## 🎭 Playwright Test Results
            
            Test run completed for commit \${{ github.sha }}
            
            📊 **Test Report:**
            - [HTML Report](https://github.com/\${{ github.repository }}/actions/runs/\${{ github.run_id }}) (Download html-report)
            
            **Browsers tested:** Chromium, Firefox
            **Run attempt:** \${{ github.run_attempt }}
            \`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });